### ISSUE TITLE
Splitting cpython doesn't work.

### ISSUE THREAD

**Issue by alex4o** [capablevms/llvm-function-split#13]
When CPython gets split it doesn't link properly. 

The splitting is done by utilizing: [whole-program-llvm](https://github.com/travitch/whole-program-llvm)

```
LLVM_COMPILER="clang" CC="wllvm" ./configure --with-lto
```

The resulting `dso_local` are stripped from the resulting bitcode file. 
Normally when it is removed the `R_X86_64_PC32 cannot be used against symbol` 
disappears. However the error still remains for the `_Py_ctype_table` global.

full linker error: 
```
make: *** [Makefile:13: lib_complex_from_string_inner.so] Error 1
ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol _Py_ctype_table; recompile with -fPIC
>>> defined in /tmp/_convertitem-2d536a.o
>>> referenced by getargs.c:524 (Python/getargs.c:524)
>>>               /tmp/_convertitem-2d536a.o:(convertitem)
```
This is how the global looks like. It is a constant and it get's copied to each of it's users. 
```
@_Py_ctype_table = local_unnamed_addr constant <{ [124 x i32], [133 x i32] }> <{ [123 x i32] [i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 8, i32 8, i32 
, i32 8, i32 8, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 8, i32 0, i32 0, i32 0, i32 0
 i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 20, i32 20, i32 20, i32 20, i32 20, i32 20, i32 20, i32 20, i32 20, i32 20, i32 0, i32 0, i32
0, i32 0, i32 0, i32 0, i32 0, i32 18, i32 18, i32 18, i32 18, i32 18, i32 18, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 2
 i32 2, i32 2, i32 2, i32 2, i32 2, i32 2, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 17, i32 17, i32 17, i32 17, i32 17, i32 17, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, 
32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1], [133 x i32] zeroinitializer }>, align 16, !dbg !2526
```

Here is the instruction accessing the constant. As it is only reading I don't see how this can be a problem. 
```
%50 = getelementptr [256 x i32], [256 x i32]* bitcast (<{ [123 x i32], [133 x i32] }>* @_Py_ctype_table to [256 x i32]*), i64 0, i64 %49, !dbg !65225
%51 = load i32, i32* %50, align 4, !dbg !65225, !tbaa !65226
```

**Comment by ltratt** [comment]
Is this an LLVM bug that we can report upstream?

**Comment by cristianurlea** [comment]
Try again with  `LLVM_COMPILER="clang" CC="wllvm" ./configure --with-lto **--enable-shared**`

**Comment by alex4o** [comment]
I am not sure if this is a bug in llvm, in wllvm or even at what stage is the problem. 
@cristianurlea I tried this, but this just builds the interpreter in a separate shared library which doesn't work for me.

**Comment by alex4o** [comment]
This was not exactly fixed. But it turns out that the code works perfectly fine with llvm-12 and [cheri-llvm](https://github.com/CTSRD-CHERI/llvm-project/). This can be closed as https://github.com/capablevms/llvm-function-split/pull/11 is merged.
