### ISSUE TITLE
Global "const type *const"

### ISSUE THREAD

**Issue by drpdr** [capablevms/llvm-function-split#19]
Global variables of any type declared as `const TYPE *const` are not correctly handled. 
During the joining phase (after every function has been correctly split) errors arise while linking all the shared libraries created because of `undefined symbols`. It seems the symbol(s) are present after having checked related `bitcode` dumps. Notwithstanding, after disassembling it with `llvm-dis` the `.ll` files do not contain any definition of the variable.

This issue was found by analysing [Postgres 9.6](https://github.com/postgres/postgres/blob/a4116b8d5a4f68803452d8f1aa3f74f302049a90/src/backend/access/heap/tuptoaster.c#L1335).

Note: to reproduce the issue [wllvm](https://github.com/travitch/whole-program-llvm) is needed.
Gzip attached with extracted bitcode (from step 2.).

There are two `.c` files and one `.h` file:

```
// File: pgcommon.h
// Global variable

extern const int *const whatever;
```

```
// File: pgcommon.c

#include "pgcommon.h"

const int val = 15;
// Issue here: the linker cannot find `val`, i.e. undefined symbol error
const int *const whatever = &val;

int pglz_compress2(const int *whatever)
{
    return *whatever;
}
```

``` 
// File: pgcommon_main.c

#include <stdio.h>
#include "pgcommon.h"

int main(void)
{	
	int what = pglz_compress2(whatever);
	printf("Just trying to reproduce the bug...\n");

	return 0;
}
```

Necessary steps:

1. `wllvm pgcommon_main.c pgcommon.c -o pgcommon_test`
2. `extract-bc pgcommon_test`
3. `split-llvm-extract pgcommon_test.bc -o out-pg` ([split.tar.gz](https://github.com/capablevms/llvm-function-split/files/7675129/split.tar.gz))
4. `cd out-pg`
5. `make`

[issue.tar.gz](https://github.com/capablevms/llvm-function-split/files/7670775/issue.tar.gz)

**Comment by ltratt** [comment]
Do you have a minimal example with just a couple of `.c` / `.h` files?

**Comment by drpdr** [comment]
> Do you have a minimal example with just a couple of `.c` / `.h` files?

There are two `.c` files and one `.h` file in the attached archive. The description of the issue was probably misleading about this aspect. I have included also the `.bc` file in the case someone wants to check it without compiling with `wllvm`.

**Comment by drpdr** [comment]
Let me improve the description a little bit referring to the specific parts in the archive.

**Comment by ltratt** [comment]
Is the `out-bc` directory important? Ideally we'd also include the `.c` / `.h` files as snippets inline in the issue given that they're so small!

**Comment by drpdr** [comment]
> Is the `out-bc` directory important? Ideally we'd also include the `.c` / `.h` files as snippets inline in the issue given that they're so small!

Done. Let me know if now it looks easier to understand. Thanks!

**Comment by ltratt** [comment]
Perfect!

**Comment by drpdr** [comment]
The issue is related to any variable not used in a function. In this particular case, `whatever` is used by `pglz_compress2(whatever)` in `int main(void)` but `val` is only referenced by `whatever` globally. This is a subtle case not easy to think about--that's why I think it not part of the tests.
Putting such "remaining variables" in a separate shared library fixes the issue, so I just need to handle this case in the splitter and test that everything keeps working. Handling this case means keeping track of all the variables extracted from the functions and adding only the globals which were not extracted.

**Comment by ltratt** [comment]
What's `val`?

**Comment by drpdr** [comment]
> What's `val`?

I am referring to the snippets above: `const int val = 15;`

**Comment by ltratt** [comment]
> The issue is related to any variable not used in a function. In this particular case, whatever is used by pglz_compress2(whatever) in int main(void) but val is only referenced by whatever globally.

I must admit that I can't quite parse this. Are you saying that the situation is something like:

```c
static int val = ...;
static int whatever = val;

void main() {
  <do something with whatever>
}
```

?

**Comment by drpdr** [comment]
> > The issue is related to any variable not used in a function. In this particular case, whatever is used by pglz_compress2(whatever) in int main(void) but val is only referenced by whatever globally.
> 
> I must admit that I can't quite parse this. Are you saying that the situation is something like:
> 
> ```c
> static int val = ...;
> static int whatever = val;
> 
> void main() {
>   <do something with whatever>
> }
> ```
> 
> ?

Yes.

**Comment by ltratt** [comment]
OK, so that suggests the splitter isn't picking up data dependency in constants, which sounds like it should be fixable!

**Comment by drpdr** [comment]
The solution of putting the "remaining variables" in a shared library works but I am sure is going to be a pain at some point in the future or even sooner. I have now figured out the actual problem related to stage 2 "handling global variables". I should be able to fix it.

**Comment by drpdr** [comment]
I have found a solution. I am going to do some more tests before opening the PR that fixes this issue.

**Comment by ltratt** [comment]
Excellent!
