### ISSUE TITLE
Visibility: global variables set as hidden

### ISSUE THREAD

**Issue by drpdr** [capablevms/llvm-function-split#23]
Like in #19, we are dealing with `extern const . *const` variables but also with global function declarations.

Given the following files:

```
// File: pgcommon.h

typedef struct PROBLEMATIC_STRUCT
{
    int two;
} PROBLEMATIC_STRUCT;

extern const PROBLEMATIC_STRUCT *const PROBLEMATIC_STRUCT_default;

// Global function declaration
extern int pglz_compress2(const PROBLEMATIC_STRUCT *prob);
```

```
// File: pgcommon.c
#include "pgcommon.h"

static const PROBLEMATIC_STRUCT problematic_data = {2};
const PROBLEMATIC_STRUCT *const PROBLEMATIC_STRUCT_default = &problematic_data;

int pglz_compress2(const PROBLEMATIC_STRUCT *prob)
{
    prob = PROBLEMATIC_STRUCT_default;
    return prob->two;
}
```

```
// File: pgcommon_main.c

#include <stdio.h>
#include "pgcommon.h"

int main(void)
{	
    int what = pglz_compress2(PROBLEMATIC_STRUCT_default);
    printf("Just trying to reproduce the bug. Value: %d\n", what);
    return 0;
}
```

The splitter correctly creates the variable `problematic_data` but marks it as `hidden`, as shown by the following disassembled bitcode:

```
; ModuleID = '_problematic_data.bc'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.PROBLEMATIC_STRUCT = type { i32 }

@problematic_data = hidden constant %struct.PROBLEMATIC_STRUCT { i32 2 }, align 4

; ... 
```

Steps to reproduce ([wllvm](https://github.com/travitch/whole-program-llvm) is needed):

1. `wllvm pgcommon_main.c pgcommon.c -o pgcommon_test`
2. `extract-bc pgcommon_test`
3. `split-llvm-extract pgcommon_test.bc -o out-v`
4. `cd out-v`
5. `CC=wllvm make`

**Comment by ltratt** [comment]
Can we reduce this example further? e.g. does the struct really need so many members?

**Comment by drpdr** [comment]
> Can we reduce this example further? e.g. does the struct really need so many members?

I think so. Let me double check.

> Also, what do we think the visibility _should_ be in such cases?

Since they are globals and then shared should be `public`. So default:
`@problematic_data = ~~hidden~~ constant %struct.PROBLEMATIC_STRUCT ...`

**Comment by drpdr** [comment]
> > Can we reduce this example further? e.g. does the struct really need so many members?
> 
> I think so. Let me double check.
> 
> > Also, what do we think the visibility _should_ be in such cases?
> 
> Since they are globals and then shared should be `public`. So default: `@problematic_data = constant %struct.PROBLEMATIC_STRUCT ...`

So public is quite wrong but "default visibility means that the declaration is visible to other modules and, in shared libraries". We need them to be visible in shared libraries, indeed.

**Comment by drpdr** [comment]
This is still one of the main issues preventing a "functional splitter". We need to "inject" this and similar code into existing tests (by expanding them). An alternative could be finding a real world simple open source project and refactor it by adding `extern`s, `cost`s variables, etc. Creating simple projects, like possible CS assignments, does not help in testing the splitter properly.

**Comment by ltratt** [comment]
Sorry, I don't understand -- can you expand the "this"s to make clear what you're referring to?

**Comment by drpdr** [comment]
> Sorry, I don't understand -- can you expand the "this"s to make clear what you're referring to?

Global variables and functions. With "this" I am referring to this issue.

**Comment by drpdr** [comment]
I have updated my comment using proper nouns and pronouns. I hope this help! Thanks!

**Comment by drpdr** [comment]
> OK, I get it now -- thanks!
> 
> However, I now disagree with something important :) I don't think this is true:
> 
> > Creating simple projects, like possible CS assignments, does not help in testing the splitter properly.
> 
> It must be possible to create examples, otherwise we wouldn't have a problem with big projects. I can believe that it is hard to either a) cut down big examples or b) construct examples out of nothing. However, I think that we need to try, at least for a while longer, as without "minimal"(ish) examples of problems, we won't know a) what we should be doing in hard cases b) whether we've done what we intended to.

Alright. I'll think again about "minimal"(ish) examples to test edge cases.
